export const CREATE_NEW_WINDOW = 'CREATE_NEW_WINDOW';
export const REMOVE_ACTIVE_WINDOW = 'REMOVE_ACTIVE_WINDOW';
export const EDIT_WINDOW = 'EDIT_WINDOW';

export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
export const SET_WINDOW_POSITION = 'SET_WINDOW_POSITION';
export const SET_WINDOW_POSITION_SIZE = 'SET_WINDOW_POSITION_SIZE';
export const SET_ACTIVE_WINDOW = 'SET_ACTIVE_WINDOW';
export const UNSET_ACTIVE_WINDOW = 'UNSET_ACTIVE_WINDOW';
export const SET_WINDOW_CONTENT = 'SET_WINDOW_CONTENT'; 

export const UNDO = 'UNDO';
export const REDO = 'REDO';
export const SAVE = 'SAVE';
export const PROCESS_UNDO_OR_REDO = 'PROCESS_UNDO_OR_REDO';